<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Example 2: Cherry trees | main.knit</title>
  <meta name="description" content="S2Y Lab 6<br />
Hypothesis testing and interval estimation</div>" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Example 2: Cherry trees | main.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Example 2: Cherry trees | main.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="example-1-modelling-college-grades.html"/>
<link rel="next" href="exercise-1-body-fat.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome to S2Y Lab 6</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#the-summary-function-for-regression-models"><i class="fa fa-check"></i><b>1.1</b> The <code>summary()</code> function for regression models</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#hypothesis-testing-for-linear-relationships"><i class="fa fa-check"></i><b>1.2</b> Hypothesis testing for linear relationships</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#finding-the-estimate-of-error-variance"><i class="fa fa-check"></i><b>1.2.1</b> Finding the estimate of error variance</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#steps-of-the-hypothesis-test"><i class="fa fa-check"></i><b>1.2.2</b> Steps of the hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#confidence-intervals-for-the-model-parameters"><i class="fa fa-check"></i><b>1.3</b> Confidence intervals for the model parameters</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#confidence-interval-for-the-population-mean-response-and-prediction-interval-for-a-future-response"><i class="fa fa-check"></i><b>1.4</b> Confidence interval for the population mean response and prediction interval for a future response</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="example-1-modelling-college-grades.html"><a href="example-1-modelling-college-grades.html"><i class="fa fa-check"></i><b>2</b> Example 1: Modelling College Grades</a>
<ul>
<li class="chapter" data-level="2.1" data-path="example-1-modelling-college-grades.html"><a href="example-1-modelling-college-grades.html#hypothsis-testing-for-regression-models"><i class="fa fa-check"></i><b>2.1</b> Hypothsis Testing for Regression Models</a></li>
<li class="chapter" data-level="2.2" data-path="example-1-modelling-college-grades.html"><a href="example-1-modelling-college-grades.html#confidence-intervals-for-model-parameters"><i class="fa fa-check"></i><b>2.2</b> Confidence intervals for model parameters</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="example-2-cherry-trees.html"><a href="example-2-cherry-trees.html"><i class="fa fa-check"></i><b>3</b> Example 2: Cherry trees</a>
<ul>
<li class="chapter" data-level="3.1" data-path="example-2-cherry-trees.html"><a href="example-2-cherry-trees.html#exploratory-analysis"><i class="fa fa-check"></i><b>3.1</b> Exploratory analysis</a></li>
<li class="chapter" data-level="3.2" data-path="example-2-cherry-trees.html"><a href="example-2-cherry-trees.html#statistical-analysis"><i class="fa fa-check"></i><b>3.2</b> Statistical analysis</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="example-2-cherry-trees.html"><a href="example-2-cherry-trees.html#hypothesis-testing-on-model-parameters"><i class="fa fa-check"></i><b>3.2.1</b> Hypothesis testing on model parameters</a></li>
<li class="chapter" data-level="3.2.2" data-path="example-2-cherry-trees.html"><a href="example-2-cherry-trees.html#confidence-interval-on-model-parameters"><i class="fa fa-check"></i><b>3.2.2</b> Confidence interval on model parameters</a></li>
<li class="chapter" data-level="3.2.3" data-path="example-2-cherry-trees.html"><a href="example-2-cherry-trees.html#confidence-interval-for-the-population-mean-response-and-prediction-interval-for-a-future-response-1"><i class="fa fa-check"></i><b>3.2.3</b> Confidence interval for the population mean response and prediction interval for a future response</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exercise-1-body-fat.html"><a href="exercise-1-body-fat.html"><i class="fa fa-check"></i><b>4</b> Exercise 1: Body fat</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><div class="line-block">S2Y Lab 6<br />
Hypothesis testing and interval estimation</div></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="example-2-cherry-trees" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Example 2: Cherry trees<a href="example-2-cherry-trees.html#example-2-cherry-trees" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The <code>trees</code> dataset in <code>R</code> give the volume (in cubic feet), diameter (in inches), and height (in feet) for a sample of 31 black cherry trees in the Allegheny National Forest, Pennsylvania. The data were collected in order to find an estimate for the volume of a tree (and therefore its timber yield), given its height and diameter. A starting point for estimating volume using these data is the geometric formula for a cylinder:</p>
<p><span class="math display">\[\mathrm{volume} = \pi \times \left(\frac{\mathrm{diameter}}{2}\right)^2\times \mathrm{height}\]</span></p>
<p>Since the underlying geometric model involves the multiplication of the two predictors of interest, we apply a log transformation to convert them in an additive term and obtain the following multiple linear regression model:</p>
<p><span class="math display" id="eq:TreesMLR">\[\begin{equation}
\log(\mathrm{volume}_i) = \alpha+\beta \log(\mathrm{diameter}_i)+\gamma \log(\mathrm{height}_i)+\epsilon_i, \quad \epsilon_i \sim N(0, \sigma^2), \quad i=1,\ldots,31 \tag{3.1}
\end{equation}\]</span></p>
<p>Now the question of interest is how to model the relationship between log(volume) (<span class="math inline">\(y\)</span>) and log(diameter) (<span class="math inline">\(x_1\)</span>) and log(height) (<span class="math inline">\(x_2\)</span>).</p>
<p>To open the dataset and apply the log-transformation, type:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="example-2-cherry-trees.html#cb21-1" tabindex="-1"></a><span class="co"># library(stats) #package automatically loaded in R</span></span>
<span id="cb21-2"><a href="example-2-cherry-trees.html#cb21-2" tabindex="-1"></a>trees <span class="ot">&lt;-</span> trees</span>
<span id="cb21-3"><a href="example-2-cherry-trees.html#cb21-3" tabindex="-1"></a></span>
<span id="cb21-4"><a href="example-2-cherry-trees.html#cb21-4" tabindex="-1"></a>trees1 <span class="ot">&lt;-</span> <span class="fu">log</span>(trees)</span>
<span id="cb21-5"><a href="example-2-cherry-trees.html#cb21-5" tabindex="-1"></a><span class="fu">colnames</span>(trees1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;logdiam&quot;</span>, <span class="st">&quot;loght&quot;</span>, <span class="st">&quot;logvol&quot;</span>)</span>
<span id="cb21-6"><a href="example-2-cherry-trees.html#cb21-6" tabindex="-1"></a>trees1 <span class="ot">&lt;-</span> trees1[,<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>)] <span class="co">#move the response variable to first column to facilitate the subsequent visualisation</span></span></code></pre></div>
<div id="exploratory-analysis" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Exploratory analysis<a href="example-2-cherry-trees.html#exploratory-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A matrix plot with scatterplots between each pair of variables can be used to gain an initial impression. This can be produced by using the following command in <code>R</code>:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="example-2-cherry-trees.html#cb22-1" tabindex="-1"></a><span class="fu">pairs</span>(trees1, <span class="at">lower.panel =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:TreesPlot1"></span>
<img src="main_files/figure-html/TreesPlot1-1.png" alt="Scatterplot displaying the relationships between the three variables." width="672" />
<p class="caption">
Figure 3.1: Scatterplot displaying the relationships between the three variables.
</p>
</div>
<p>The argument <code>lower.panel = NULL</code> only displays the top diagonal of the matrix which ensures the response of log(volume) is on the y-axis of the plots. It may be more appropriate to use <code>upper.panel = NULL</code> depending on the position of the response variable in the dataframe. Figure <a href="example-2-cherry-trees.html#fig:TreesPlot1">3.1</a> shows the relationships between the three variables.</p>
<p><strong>DISCUSSION</strong>: What can we say about the relationships between the three variables?</p>
</div>
<div id="statistical-analysis" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Statistical analysis<a href="example-2-cherry-trees.html#statistical-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>TASK</strong>: Fit the multiple linear regression model in formula <a href="example-2-cherry-trees.html#eq:TreesMLR">(3.1)</a> and display the summary of the model.</p>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="example-2-cherry-trees.html#cb23-1" tabindex="-1"></a>Model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logvol <span class="sc">~</span> logdiam <span class="sc">+</span> loght, <span class="at">data =</span> trees1)</span>
<span id="cb23-2"><a href="example-2-cherry-trees.html#cb23-2" tabindex="-1"></a><span class="fu">summary</span>(Model3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logvol ~ logdiam + loght, data = trees1)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.168561 -0.048488  0.002431  0.063637  0.129223 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -6.63162    0.79979  -8.292 5.06e-09 ***
## logdiam      1.98265    0.07501  26.432  &lt; 2e-16 ***
## loght        1.11712    0.20444   5.464 7.81e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.08139 on 28 degrees of freedom
## Multiple R-squared:  0.9777, Adjusted R-squared:  0.9761 
## F-statistic: 613.2 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="hypothesis-testing-on-model-parameters" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Hypothesis testing on model parameters<a href="example-2-cherry-trees.html#hypothesis-testing-on-model-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To decide if the predictors are useful, we perform a hypothesis test for each of the parameters:</p>
<p><span class="math display">\[H_0: \beta = 0 \ /\ \gamma = 0 \quad \text{vs.} \quad H_1: \beta \ne 0 \ / \ \gamma \ne 0\]</span></p>
<p><strong>QUESTION</strong>: Based on the model summary produced in <code>R</code>, what can you conclude about the usefulness of log(diameter) and log(height) in predicting log(volume)?</p>
<div id="radio_QVEOWHBQYN" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_QVEOWHBQYN" value=""></input> <span>log(diameter) is a statistically significant predictor of log(volume)</span></label><label><input type="radio" autocomplete="off" name="radio_QVEOWHBQYN" value="answer"></input> <span>log(diameter) is a statistically significant predictor of log(volume) in addition to log(height).</span></label><label><input type="radio" autocomplete="off" name="radio_QVEOWHBQYN" value=""></input> <span>log(diameter) is not a statistically significant predictor of log(volume).</span></label><label><input type="radio" autocomplete="off" name="radio_QVEOWHBQYN" value=""></input> <span>We cannot conclude if log(diameter) is a statistically significant predictor of log(volume).</span></label>
</div>
<div id="radio_XZBEBLBRYP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_XZBEBLBRYP" value=""></input> <span>log(height) is a statistically significant predictor of log(volume).</span></label><label><input type="radio" autocomplete="off" name="radio_XZBEBLBRYP" value="answer"></input> <span>log(height) is a statistically significant predictor of log(volume) in addition to log(diameter).</span></label><label><input type="radio" autocomplete="off" name="radio_XZBEBLBRYP" value=""></input> <span>log(height) is not a statistically significant predictor of log(volume) in addition to log(diameter).</span></label><label><input type="radio" autocomplete="off" name="radio_XZBEBLBRYP" value=""></input> <span>We cannot conclude if log(height) is a statistically significant predictor of log(volume).</span></label>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<p>Since the <span class="math inline">\(p\)</span>-values for <code>logdiam</code> and <code>loght</code> are both <span class="math inline">\(&lt; 0.001\)</span> (indicated by the significance codes in <code>R</code> '***'), the null hypothesis <span class="math inline">\(H_0\)</span> is rejected and we conclude that log(diameter) is a statistically significant predictor of log(volume) in addition to log(height), and log(height) is a statistically significant predictor of log(volume) in addition to log(diameter).</p>
</div>
</div>
<div id="confidence-interval-on-model-parameters" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Confidence interval on model parameters<a href="example-2-cherry-trees.html#confidence-interval-on-model-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>QUESTION</strong>:</p>
<ul>
<li><p>The 95% confidence interval for <span class="math inline">\(\beta\)</span> is (<input class='webex-solveme nospaces' size='8' data-answer='["1.828998","1.829","1.83"]'/>, <input class='webex-solveme nospaces' size='8' data-answer='["2.136302","2.1363","2.136","2.14"]'/>).</p></li>
<li><p>The 95% confidence interval for <span class="math inline">\(\gamma\)</span> is (<input class='webex-solveme nospaces' size='7' data-answer='["0.69835","0.6984","0.698","0.7",".69835",".6984",".698",".7"]'/>, <input class='webex-solveme nospaces' size='8' data-answer='["1.535894","1.53589","1.5359","1.536","1.54"]'/>).</p></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Calculate using the formula <a href="index.html#eq:CI">(1.1)</a> or use the R function <code>confint()</code>.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<p><strong>confidence interval for <span class="math inline">\(\hat{\beta}\)</span></strong></p>
<p>From the regression output, we know <span class="math inline">\(\hat{\beta}\)</span> (the coefficient, estimate of the model parameter) and the estimated standard error for the parameter, which are 1.98265 and 0.07501 respectively.</p>
<p>We could also verify the result of estimated standard error. We know that</p>
<p><span class="math display">\[\hat{\sigma} = 0.08139 \quad\quad\quad\quad\quad n-p = 31 - 3 = 28,\]</span>
and <span class="math inline">\((\mathbf{X}^\top\mathbf{X})^{-1}\)</span> can be computed by using</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="example-2-cherry-trees.html#cb25-1" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> logdiam <span class="sc">+</span> loght, <span class="at">data =</span> trees1)</span>
<span id="cb25-2"><a href="example-2-cherry-trees.html#cb25-2" tabindex="-1"></a>XTXI <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X)</span>
<span id="cb25-3"><a href="example-2-cherry-trees.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="example-2-cherry-trees.html#cb25-4" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb25-5"><a href="example-2-cherry-trees.html#cb25-5" tabindex="-1"></a><span class="co"># XTXI &lt;- summary(Model3)$cov.unscaled</span></span></code></pre></div>
<p>which gives
<span class="math display">\[(\mathbf{X}^\top\mathbf{X})^{-1} = \begin{bmatrix}
96.572067 &amp; 3.1392672 &amp; -24.165092\\
3.139267 &amp; 0.8494646 &amp; -1.227489\\
-24.165092 &amp; -1.2274894 &amp; 6.309851
\end{bmatrix}\]</span></p>
<p>Therefore, the estimated standard error for <span class="math inline">\(\beta\)</span> is given by</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="example-2-cherry-trees.html#cb26-1" tabindex="-1"></a><span class="fl">0.08139</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fl">0.8494646</span>)</span></code></pre></div>
<pre><code>## [1] 0.07501424</code></pre>
<p>To calculate the confidence interval, it remains to find the 0.975th quantile of the <span class="math inline">\(t\)</span>-distribution with 28 degrees of freedom, and we do this in <code>R</code> as follows:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="example-2-cherry-trees.html#cb28-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">28</span>)</span></code></pre></div>
<pre><code>## [1] 2.048407</code></pre>
<p>Therefore, a 95% confidence interval for <span class="math inline">\(\beta\)</span> can be found by computing:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="example-2-cherry-trees.html#cb30-1" tabindex="-1"></a><span class="fl">1.98265</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> <span class="fl">2.048407</span> <span class="sc">*</span> <span class="fl">0.07501424</span></span></code></pre></div>
<pre><code>## [1] 1.82899 2.13631</code></pre>
<p><strong>confidence interval for <span class="math inline">\(\gamma\)</span></strong></p>
<p>In a similar manner, we can find the confidence interval for <span class="math inline">\(\gamma\)</span> as follows:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="example-2-cherry-trees.html#cb32-1" tabindex="-1"></a><span class="fl">1.11712</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> <span class="fl">2.048407</span> <span class="sc">*</span> <span class="fl">0.20444</span></span>
<span id="cb32-2"><a href="example-2-cherry-trees.html#cb32-2" tabindex="-1"></a><span class="co">#estimate +/- t_value * estimated standard error</span></span>
<span id="cb32-3"><a href="example-2-cherry-trees.html#cb32-3" tabindex="-1"></a></span>
<span id="cb32-4"><a href="example-2-cherry-trees.html#cb32-4" tabindex="-1"></a><span class="co">#The estimated standard error is computed as</span></span>
<span id="cb32-5"><a href="example-2-cherry-trees.html#cb32-5" tabindex="-1"></a><span class="fl">0.08139</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fl">6.309851</span>)</span></code></pre></div>
<p>Both intervals can be computed simultaneously in using the following command:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="example-2-cherry-trees.html#cb33-1" tabindex="-1"></a><span class="fu">confint</span>(Model3)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) -8.269912 -4.993322
## logdiam      1.828998  2.136302
## loght        0.698353  1.535894</code></pre>
</div>
<p><strong>QUESTION</strong>: What conclusions can be drawn from these confidence intervals?</p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The coefficient for log(diameter) is highly likely to lie between 1.83 and 2.14. As this interval does not contain 0, we conclude that the predictor log(diameter) makes a statistically significant contribution in addition to the predictor log(height) in explaining the variability in log(volume). Therefore log(diameter) is retained in the model, in addition to log(height).</p>
<p>The coefficient for log(height) is highly likely to lie between 0.70 and 1.54. As this interval does not contain 0, we conclude that the predictor log(height) makes a statistically significant contribution in addition to the predictor log(diameter) in explaining the variability in log(volume). Therefore log(height) is retained in the model, in addition to log(diameter).</p>
</div>
</div>
<div id="confidence-interval-for-the-population-mean-response-and-prediction-interval-for-a-future-response-1" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Confidence interval for the population mean response and prediction interval for a future response<a href="example-2-cherry-trees.html#confidence-interval-for-the-population-mean-response-and-prediction-interval-for-a-future-response-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once we have fitted the model of interest it may also be useful to compute further confidence and prediction intervals from the fitted model. For example,</p>
<ol style="list-style-type: decimal">
<li>Suppose that we consider a population of cherry trees for which the log(diameter) is 2.4 and the log(height) is 4.3. Provide a 95% confidence interval for the mean log(volume) in this population of cherry trees. Interpret the interval.</li>
<li>Suppose, now, that we wish to obtain a 95% prediction interval for an individual cherry tree in the population which has a log(diameter) of 2.4 and a log(height) of 4.3. Interpret the interval.</li>
</ol>
<p>We use <code>R</code> to compute the required intervals.</p>
<p><strong>95% confidence interval for the population mean:</strong></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="example-2-cherry-trees.html#cb35-1" tabindex="-1"></a>predframe <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">logdiam =</span> <span class="fl">2.4</span>, <span class="at">loght =</span> <span class="fl">4.3</span>)</span>
<span id="cb35-2"><a href="example-2-cherry-trees.html#cb35-2" tabindex="-1"></a><span class="fu">predict</span>(Model3, <span class="at">int =</span> <span class="st">&quot;c&quot;</span>, <span class="at">newdata =</span> predframe)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 2.930373 2.894059 2.966686</code></pre>
<p>The <code>data.frame</code> command creates a table; each column represents one variable and each row contains one set of values from each column. The <code>predict</code> command can produce both a confidence interval and a prediction interval. To obtain a confidence interval we use the argument <code>int = "c"</code>.</p>
<p>Therefore we conclude that in a population of cherry trees for which the log(diameter) is 2.4 and the log(height) is 4.3 it is highly likely that the log(volume) would lie, on average, somewhere between 2.89 and 2.97.</p>
<p><strong>95% prediction interval for a future tree:</strong></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="example-2-cherry-trees.html#cb37-1" tabindex="-1"></a><span class="fu">predict</span>(Model3, <span class="at">int =</span> <span class="st">&quot;p&quot;</span>, <span class="at">newdata =</span> predframe)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 2.930373 2.759752 3.100994</code></pre>
<p>The argument <code>int = "p"</code> in the <code>predict</code> command provides a prediction interval based on the specified values in the new dataframe <code>predframe</code>. Therefore if a cherry tree with a log(diameter) of 2.4 and a log(height) of 4.3 were selected randomly from the population of cherry trees, it is highly likely that it would have a log volume of somewhere between 2.76 and 3.10. Comparing with the 95% confidence interval, the 95% prediction interval has a wider range.</p>
<p><strong>TASK</strong> (challenging): Verify that the above results are correct by computing the confidence interval and prediction interval using formulas <a href="index.html#eq:CImean">(1.2)</a> and <a href="index.html#eq:PI">(1.3)</a>.</p>
<p>Feel free to ask tutors for help if you can't solve this task.</p>

</div>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="example-1-modelling-college-grades.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exercise-1-body-fat.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["main.pdf", "main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
