<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Example 1: log-transformation on \(x\) | main.knit</title>
  <meta name="description" content="S2Y Lab 5<br />
Further examination on model fit and assumptions - ANOVA, residual plots and transformations</div>" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Example 1: log-transformation on \(x\) | main.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Example 1: log-transformation on \(x\) | main.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="example-2-power-transformation-on-y.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome to S2Y Lab 5</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="example-1-log-transformation-on-x.html"><a href="example-1-log-transformation-on-x.html"><i class="fa fa-check"></i><b>2</b> Example 1: log-transformation on <span class="math inline">\(x\)</span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="example-1-log-transformation-on-x.html"><a href="example-1-log-transformation-on-x.html#exploratory-analysis"><i class="fa fa-check"></i><b>2.1</b> Exploratory analysis</a></li>
<li class="chapter" data-level="2.2" data-path="example-1-log-transformation-on-x.html"><a href="example-1-log-transformation-on-x.html#statistical-analysis"><i class="fa fa-check"></i><b>2.2</b> Statistical analysis</a></li>
<li class="chapter" data-level="2.3" data-path="example-1-log-transformation-on-x.html"><a href="example-1-log-transformation-on-x.html#assumption-checking"><i class="fa fa-check"></i><b>2.3</b> Assumption checking</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="example-2-power-transformation-on-y.html"><a href="example-2-power-transformation-on-y.html"><i class="fa fa-check"></i><b>3</b> Example 2: power transformation on <span class="math inline">\(y\)</span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="example-2-power-transformation-on-y.html"><a href="example-2-power-transformation-on-y.html#exploratory-analysis-1"><i class="fa fa-check"></i><b>3.1</b> Exploratory analysis</a></li>
<li class="chapter" data-level="3.2" data-path="example-2-power-transformation-on-y.html"><a href="example-2-power-transformation-on-y.html#assumption-checking-1"><i class="fa fa-check"></i><b>3.2</b> Assumption checking</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="example-2-power-transformation-on-y.html"><a href="example-2-power-transformation-on-y.html#regression-output"><i class="fa fa-check"></i><b>3.2.1</b> Regression output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="optional-activity-more-on-log-transformation.html"><a href="optional-activity-more-on-log-transformation.html"><i class="fa fa-check"></i><b>4</b> Optional activity: more on log-transformation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="optional-activity-more-on-log-transformation.html"><a href="optional-activity-more-on-log-transformation.html#log-transformation-on-y"><i class="fa fa-check"></i><b>4.1</b> Log-transformation on <span class="math inline">\(y\)</span></a></li>
<li class="chapter" data-level="4.2" data-path="optional-activity-more-on-log-transformation.html"><a href="optional-activity-more-on-log-transformation.html#log-transformation-on-both-x-and-y"><i class="fa fa-check"></i><b>4.2</b> log-transformation on both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="solution.html"><a href="solution.html"><i class="fa fa-check"></i><b>5</b> Solution</a>
<ul>
<li class="chapter" data-level="5.1" data-path="solution.html"><a href="solution.html#task-1"><i class="fa fa-check"></i><b>5.1</b> Task 1</a></li>
<li class="chapter" data-level="5.2" data-path="solution.html"><a href="solution.html#task-2"><i class="fa fa-check"></i><b>5.2</b> Task 2</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><div class="line-block">S2Y Lab 5<br />
Further examination on model fit and assumptions - ANOVA, residual plots and transformations</div></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="example-1-log-transformation-on-x" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Example 1: log-transformation on <span class="math inline">\(x\)</span><a href="example-1-log-transformation-on-x.html#example-1-log-transformation-on-x" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Rossman (1994) collected information on life expectancy in various countries of the world and the densities of people per television set and of people per physician in those countries. The data is available in the <code>LifeExp.csv</code> file.</p>
<p>In this lab, our focus is to identify how female life expectancy (<span class="math inline">\(Y\)</span>, abbreviated to FLE) is related to the number of people per physician (<span class="math inline">\(x\)</span>, abbreviated to PPP).</p>
<div id="exploratory-analysis" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Exploratory analysis<a href="example-1-log-transformation-on-x.html#exploratory-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Firstly, produce a scatterplot of FLE against PPP by typing:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="example-1-log-transformation-on-x.html#cb1-1" aria-hidden="true" tabindex="-1"></a>life <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;LifeExp.csv&quot;</span>)</span>
<span id="cb1-2"><a href="example-1-log-transformation-on-x.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(FLE <span class="sc">~</span> PPP, <span class="at">data =</span> life)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="main_files/figure-html/unnamed-chunk-4-1.png" alt="Scatterplot of female life expectancy versus the number of people per physician." width="70%" />
<p class="caption">
Figure 2.1: Scatterplot of female life expectancy versus the number of people per physician.
</p>
</div>
<p><strong>DISCUSSION</strong>: Looking at the plot, what can we say about the relationship between female life expectancy and the number of people per physician?</p>
<p>As the relationship appears to be non-linear, we apply log-transformation to the predictor variable. Transforming the values of <span class="math inline">\(x\)</span> might be the first thing to try if there is a non-linear monotonic (i.e. entirely non-increasing or entirely non-decreasing) trend in the data, and non-linearity is the only problem. In other words, model assumptions (i.e. independence, zero-mean, constant variance, normality) should be met. The scatterplot of female life expectancy against <span class="math inline">\(\log\)</span>(PPP) is produced by typing:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="example-1-log-transformation-on-x.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(FLE <span class="sc">~</span> <span class="fu">log</span>(PPP), <span class="at">data =</span> life, <span class="at">xlab =</span> <span class="st">&quot;log(PPP)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:logX"></span>
<img src="main_files/figure-html/logX-1.png" alt="Scatterplot of female life expectancy versus log(number of people per physician)." width="70%" />
<p class="caption">
Figure 2.2: Scatterplot of female life expectancy versus log(number of people per physician).
</p>
</div>
<p>Figure <a href="example-1-log-transformation-on-x.html#fig:logX">2.2</a> shows a linear trend after transforming <span class="math inline">\(x\)</span>. Therefore, we will model the relationship between FLE and <span class="math inline">\(\log\)</span>(PPP) using a simple linear regression model. The model is given as:
<span class="math display">\[Y_i = \alpha + \beta \log(x_i) + \epsilon_i,\quad \epsilon_i \sim N(0,\sigma^2), \quad i = 1,\ldots, 37.\]</span></p>
</div>
<div id="statistical-analysis" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Statistical analysis<a href="example-1-log-transformation-on-x.html#statistical-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A simple linear regression model can be fitted by using the <code>lm</code> command:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="example-1-log-transformation-on-x.html#cb3-1" aria-hidden="true" tabindex="-1"></a>Model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(FLE <span class="sc">~</span> <span class="fu">log</span>(PPP), <span class="at">data =</span> life)</span></code></pre></div>
<p>The summary table and ANOVA table of this model can be produced by using <code>summary()</code> and <code>anova()</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="example-1-log-transformation-on-x.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = FLE ~ log(PPP), data = life)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.065 -3.489  1.143  2.663  7.674 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 109.9498     3.6860   29.83  &lt; 2e-16 ***
## log(PPP)     -5.4893     0.5036  -10.90 8.48e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.286 on 35 degrees of freedom
## Multiple R-squared:  0.7724, Adjusted R-squared:  0.7659 
## F-statistic: 118.8 on 1 and 35 DF,  p-value: 8.484e-13</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="example-1-log-transformation-on-x.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Model1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: FLE
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## log(PPP)   1 2182.34 2182.34  118.81 8.484e-13 ***
## Residuals 35  642.91   18.37                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>QUESTION</strong>:</p>
<ol style="list-style-type: lower-alpha">
<li>Using the following summary statistics, calculate the least squares estimates of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>. Check your answers with the column of <code>Estimate</code> in the summary table.</li>
</ol>
<p><span class="math display">\[\bar{x} = 7.18,\ \bar{y} = 70.51,\ S_{xx}=72.42,\ S_{yy}=2825.24,\ S_{xy}=-397.56\]</span></p>
<!-- (*Enter your answer by rounding to two decimal places*) -->
<!-- $\hat{\alpha}$ = <input class='webex-solveme nospaces' size='6' data-answer='["109.93"]'/>  -->
<!-- $\hat{\beta}$ = <input class='webex-solveme nospaces' size='9' data-answer='["-5.489644","-5.48964","-5.4896","-5.49","-5.5"]'/> -->
<div class="webex-solution">
<button>
Hint
</button>
<p><span class="math display">\[\hat{\alpha} = \bar{y} - \hat{\beta}\bar{x},\
  \hat{\beta}  = \frac{S_{xy}}{S_{xx}}\]</span></p>
</div>
<ol start="2" style="list-style-type: lower-alpha">
<li>Write down the equation of the fitted model. Based on it, comment on the least squares estimate of <span class="math inline">\(\beta\)</span> and predict the value of female life expectancy when the number of people per physician equals 4000.</li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<p>The regression equation is
<span class="math display">\[\text{FLE} = 109.95 - 5.49 \cdot \log(\text{PPP})\]</span></p>
<p><span class="math inline">\(\hat{\beta}\)</span> can be interpreted as: if <span class="math inline">\(\log(\text{PPP})\)</span> increases by 1 unit, the expected female life expectancy decreases by 5.49.</p>
<p>When predicting the value of the response for a new observation, we need to back transform the variable. For example, if the number of people per physician is 4000, the best prediction of female life expectancy is <span class="math inline">\(109.95 - 5.49 \cdot \log(4000) \approx 64.42\)</span>.</p>
</div>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the summary statistics in (a) to complete the analysis of variance table below, i.e. finding the degrees of freedom, the sum of squares, the mean squared error, and the <span class="math inline">\(F\)</span>-statistic. Check your answer with the <code>anova</code> output.</li>
</ol>
<table>
<thead>
<tr class="header">
<th align="left">Component</th>
<th align="left">DF</th>
<th align="left">Sum Sq (SS)</th>
<th align="left">Mean Sq (MS)</th>
<th align="left">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Model</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Residual</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<ol start="4" style="list-style-type: lower-alpha">
<li>What hypotheses are being examined by the <span class="math inline">\(F\)</span>-statistic in the ANOVA table? By looking at its <span class="math inline">\(p\)</span>-value, what can you conclude about the fitted model?</li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<p>The null and alternative hypotheses are:
H<span class="math inline">\(_0\)</span>: <span class="math inline">\(\beta=0\)</span>   versus   H<span class="math inline">\(_1\)</span>: <span class="math inline">\(\beta \neq 0\)</span>
Note that <span class="math inline">\(\alpha\)</span> is not included in the hypothesis.</p>
<p>Since the <span class="math inline">\(p\)</span>-value (from <code>Pr(&gt;F)</code>) is less than 0.05, we reject the null hypothesis and conclude that <span class="math inline">\(\log\)</span>(PPP) is useful in predicting FLE.</p>
</div>
<ol start="5" style="list-style-type: lower-alpha">
<li>Compute and interpret the coefficient of determination, <span class="math inline">\(R^2\)</span>. Check your answer with the term <code>Multiple R-squared</code> in the summary table.</li>
</ol>
<div class="webex-solution">
<button>
Hint
</button>
<p><span class="math display">\[R^2 = 1-\frac{\text{RSS}}{\text{TSS}}\]</span></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{equation*}
\begin{split}
R^2 &amp;= 1-\frac{\text{RSS}}{\text{TSS}}\\
&amp;=1-\frac{642.91}{2182.34+642.91}\\
&amp;=0.772
\end{split}
\end{equation*}\]</span>
The <span class="math inline">\(R^2\)</span> tells us the model provides a relatively adequate fit to the data with 77% of variability in FLE can be explained by this model.</p>
</div>
<ol start="6" style="list-style-type: lower-alpha">
<li>Comment on the strength of linear relationship between <span class="math inline">\(\log\)</span>(PPP) and FLE.</li>
</ol>
<div class="webex-solution">
<button>
Hint
</button>
<p>The strength of a linear relationship can be quantified using the sample correlation coefficient.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<p>We could calculate the sample correlation coefficient <span class="math inline">\(r\)</span> based on its definition or use the fact that <span class="math inline">\(r^2 = R^2\)</span> in the case of simple linear regression (see Chapter 2, <span class="math inline">\(\S\)</span> 2.1)</p>
<p>Approach 1: based on the definition
<span class="math display">\[\begin{equation*}
\begin{split}
r &amp;=\frac{S_{xy}}{\sqrt{S_{xx}S_{yy}}}\\
&amp;=\frac{-397.56}{72.42\cdot 2825.24}\\
&amp;=-0.879
\end{split}
\end{equation*}\]</span></p>
<p>Approach 2: use <span class="math inline">\(r^2=R^2\)</span>
<span class="math display">\[|r|=\sqrt{R^2} = \sqrt{0.772}=0.879\]</span>
Based on the scatterplot, we know that the relationship between <span class="math inline">\(\log\)</span>(PPP) and FLE is negative, and thus <span class="math inline">\(r=-0.879\)</span>.</p>
<p>Approach 3: use the command <code>cor</code> in <code>R</code></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="example-1-log-transformation-on-x.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">log</span>(life<span class="sc">$</span>PPP),life<span class="sc">$</span>FLE)</span></code></pre></div>
<pre><code>## [1] -0.8788868</code></pre>
<p>The sample correlation coefficient of <span class="math inline">\(-0.879\)</span> tells us that there is a strong negative relationship between <span class="math inline">\(\log\)</span>(PPP) and FLE.</p>
</div>
</div>
<div id="assumption-checking" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Assumption checking<a href="example-1-log-transformation-on-x.html#assumption-checking" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As seen in Lab 4, model assumptions can be assessed graphically by producing a plot of the residuals versus the fitted values and a normal probability plot (Q-Q plot) of the residuals with the following <code>R</code> commands:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="example-1-log-transformation-on-x.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstandard</span>(Model1) <span class="sc">~</span> <span class="fu">fitted</span>(Model1))</span>
<span id="cb10-2"><a href="example-1-log-transformation-on-x.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>, <span class="at">lwd=</span><span class="fl">1.5</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ResVsFitted"></span>
<img src="main_files/figure-html/ResVsFitted-1.png" alt="Standardised residuals versus fitted values plot from fitting a simple linear regression model to transformed variables." width="672" />
<p class="caption">
Figure 2.3: Standardised residuals versus fitted values plot from fitting a simple linear regression model to transformed variables.
</p>
</div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="example-1-log-transformation-on-x.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">rstandard</span>(Model1))</span>
<span id="cb11-2"><a href="example-1-log-transformation-on-x.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">rstandard</span>(Model1))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:QQ-plot"></span>
<img src="main_files/figure-html/QQ-plot-1.png" alt="Normal probability (Q-Q) plot from fitting a simple linear regression model to transformed variables." width="672" />
<p class="caption">
Figure 2.4: Normal probability (Q-Q) plot from fitting a simple linear regression model to transformed variables.
</p>
</div>
<p>Figure <a href="example-1-log-transformation-on-x.html#fig:ResVsFitted">2.3</a> displays the residual plots after fitting a simple linear regression model to the transformed variables. The points are fairly evenly scattered above and below the zero line, which suggests it is reasonable to assume that the random errors have mean zero. The vertical variation of the points seems to be small for small fitted values. However, there are also less points in this case. It would be preferable if more data are available. In the normal probability plot (Figure <a href="example-1-log-transformation-on-x.html#fig:QQ-plot">2.4</a>), we see that points do not exactly lie on diagonal line. This indicates that the normality assumption may not necessarily be satisfied. The independence of the random errors seems to be reasonable since each point refers to a different country.</p>

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="example-2-power-transformation-on-y.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["main.pdf", "main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
