<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Example 2: Power of a test | Lab 1 -Exploring Hypothesis Testing</title>
  <meta name="description" content="3 Example 2: Power of a test | Lab 1 -Exploring Hypothesis Testing" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Example 2: Power of a test | Lab 1 -Exploring Hypothesis Testing" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Example 2: Power of a test | Lab 1 -Exploring Hypothesis Testing" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="example-1-the-5-steps-of-hypothesis-testing.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome to Lab 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#optional-rstudio-quickstart-guide"><i class="fa fa-check"></i><b>1.2</b> Optional: RStudio Quickstart Guide</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#credit-where-credit-is-due"><i class="fa fa-check"></i><b>1.3</b> Credit where credit is due</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html"><i class="fa fa-check"></i><b>2</b> Example 1: The 5 Steps of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="2.1" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#verifying-normality"><i class="fa fa-check"></i><b>2.1</b> Verifying normality</a></li>
<li class="chapter" data-level="2.2" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#step-1---hypotheses"><i class="fa fa-check"></i><b>2.2</b> <strong>Step 1 - Hypotheses</strong></a></li>
<li class="chapter" data-level="2.3" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#step-2---choosing-a-test-statistic"><i class="fa fa-check"></i><b>2.3</b> <strong>Step 2 - Choosing a Test Statistic</strong></a></li>
<li class="chapter" data-level="2.4" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#step-3---hypothesis-test-calculations"><i class="fa fa-check"></i><b>2.4</b> <strong>Step 3 - Hypothesis Test Calculations</strong></a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#finding-your-rejection-region"><i class="fa fa-check"></i><b>2.4.1</b> Finding your Rejection Region</a></li>
<li class="chapter" data-level="2.4.2" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#finding-your-standardised-test-statistic-and-p-value"><i class="fa fa-check"></i><b>2.4.2</b> Finding your standardised test statistic and p-value</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#step-4---statistical-conclusion"><i class="fa fa-check"></i><b>2.5</b> <strong>Step 4 - Statistical Conclusion</strong></a></li>
<li class="chapter" data-level="2.6" data-path="example-1-the-5-steps-of-hypothesis-testing.html"><a href="example-1-the-5-steps-of-hypothesis-testing.html#step-5---english-conclusion"><i class="fa fa-check"></i><b>2.6</b> <strong>Step 5 - English Conclusion</strong></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="example-2-power-of-a-test.html"><a href="example-2-power-of-a-test.html"><i class="fa fa-check"></i><b>3</b> Example 2: Power of a test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="example-2-power-of-a-test.html"><a href="example-2-power-of-a-test.html#question-1"><i class="fa fa-check"></i><b>3.1</b> <strong>Question 1</strong></a></li>
<li class="chapter" data-level="3.2" data-path="example-2-power-of-a-test.html"><a href="example-2-power-of-a-test.html#question-2"><i class="fa fa-check"></i><b>3.2</b> <strong>Question 2</strong></a></li>
<li class="chapter" data-level="3.3" data-path="example-2-power-of-a-test.html"><a href="example-2-power-of-a-test.html#question-3"><i class="fa fa-check"></i><b>3.3</b> <strong>Question 3</strong></a></li>
<li class="chapter" data-level="3.4" data-path="example-2-power-of-a-test.html"><a href="example-2-power-of-a-test.html#question-4"><i class="fa fa-check"></i><b>3.4</b> <strong>Question 4</strong></a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lab 1 -Exploring Hypothesis Testing</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="example-2-power-of-a-test" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Example 2: Power of a test<a href="example-2-power-of-a-test.html#example-2-power-of-a-test" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>A cell phone provider has estimated that it needs revenues of €2 million per day in order to make a profit and remain in the market. If revenues are less than €2 million per day, the company will go bankrupt. Likewise, revenues greater than €2 million per day cannot be handled without increasing staff. Assume that revenues follow a normal distribution with <span class="math inline">\(\sigma =\)</span> €0.5 million and a mean of <span class="math inline">\(\mu\)</span>.</p>
<p>To find out more about their revenue they want to perform a hypothesis test <span class="math inline">\(H_0 : \mu = 2\)</span> versus <span class="math inline">\(H_1 : \mu \neq 2\)</span>. To understand more about how hypothesis tests work, three scenarios will be presented to show how the power of a test can change: varying mu, varying significance level and varying sample size.</p>
<p>The power function is:</p>
<p><span class="math display">\[Power(\theta) = P(\text{reject }H_0|H_0 \text{ is false}) = P(\text{accept }H_1|H1)\]</span>
<span class="math display">\[Power(\theta) = 1-\beta(\theta)\]</span></p>
<p>where <span class="math inline">\(\beta(\theta)\)</span> is the probability of a type II error at a given <span class="math inline">\(\theta\)</span></p>
<div id="question-1" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> <strong>Question 1</strong><a href="example-2-power-of-a-test.html#question-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Graphically depict the power function for testing <span class="math inline">\(H_0 : \mu = 2\)</span> versus <span class="math inline">\(H_1 : \mu \neq 2\)</span> if
<span class="math inline">\(n = 150\)</span> and <span class="math inline">\(\alpha = 0.05\)</span> for values of <span class="math inline">\(\mu\)</span> ranging from 1.8 to 2.2.</p>
<div class="webex-solution">
<button>
Hint 1
</button>
<p>Think about whether you are doing a one or two-tailed test and what values represent rejecting or no-rejecting them.</p>
</div>
<div class="webex-solution">
<button>
Hint 2
</button>
<p>First make a vector of values of <span class="math inline">\(\mu\)</span>.</p>
<p>Then you will need to find the confidence values for our significance level <span class="math inline">\(\alpha\)</span> which are used to calculate the power can be found for each <span class="math inline">\(\mu\)</span>.</p>
<p>The power values could be to be written as a data frame to make the plotting easier.</p>
</div>
<div class="webex-solution">
<button>
Calculations Solution
</button>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="example-2-power-of-a-test.html#cb18-1" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">1.8</span>, <span class="at">to =</span> <span class="fl">2.2</span>, <span class="at">length =</span> <span class="dv">500</span>)</span>
<span id="cb18-2"><a href="example-2-power-of-a-test.html#cb18-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">150</span></span>
<span id="cb18-3"><a href="example-2-power-of-a-test.html#cb18-3" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb18-4"><a href="example-2-power-of-a-test.html#cb18-4" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb18-5"><a href="example-2-power-of-a-test.html#cb18-5" tabindex="-1"></a></span>
<span id="cb18-6"><a href="example-2-power-of-a-test.html#cb18-6" tabindex="-1"></a>lcv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb18-7"><a href="example-2-power-of-a-test.html#cb18-7" tabindex="-1"></a>ucv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb18-8"><a href="example-2-power-of-a-test.html#cb18-8" tabindex="-1"></a></span>
<span id="cb18-9"><a href="example-2-power-of-a-test.html#cb18-9" tabindex="-1"></a>Power <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(lcv, mu, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n)) <span class="sc">+</span> <span class="fu">pnorm</span>(ucv, mu, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n), <span class="at">lower =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-10"><a href="example-2-power-of-a-test.html#cb18-10" tabindex="-1"></a></span>
<span id="cb18-11"><a href="example-2-power-of-a-test.html#cb18-11" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mu, Power)</span></code></pre></div>
</div>
<div class="webex-solution">
<button>
Plot Solution
</button>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="example-2-power-of-a-test.html#cb19-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> DF, <span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> Power)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="example-2-power-of-a-test.html#cb19-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="example-2-power-of-a-test.html#cb19-3" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="example-2-power-of-a-test.html#cb19-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu), <span class="at">y =</span> <span class="fu">expression</span>(Power<span class="sc">~</span>(mu))) <span class="sc">+</span></span>
<span id="cb19-5"><a href="example-2-power-of-a-test.html#cb19-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
</div>
<div id="question-2" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> <strong>Question 2</strong><a href="example-2-power-of-a-test.html#question-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Graphically depict the power function for testing <span class="math inline">\(H_0 : \mu = 2\)</span> versus <span class="math inline">\(H_1 : \mu \neq 2\)</span> when <span class="math inline">\(\mu_1 = 2.1\)</span> and <span class="math inline">\(n = 150\)</span> for values of <span class="math inline">\(\alpha\)</span> ranging from 0.001 to 0.999.</p>
<div class="webex-solution">
<button>
Hint 1
</button>
<p>Think about whether you are doing a one or two-tailed test and what values represent rejecting or no-rejecting them.</p>
</div>
<div class="webex-solution">
<button>
Hint 2
</button>
<p>First make a vector of values of <span class="math inline">\(\alpha\)</span>.</p>
<p>Then you will need to find the confidence values for each <span class="math inline">\(\alpha\)</span> which are used to calculate the corresponding test powers.</p>
<p>The power values could be to be written as a data frame to make the plotting easier.</p>
</div>
<div class="webex-solution">
<button>
Calculations Solution
</button>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="example-2-power-of-a-test.html#cb20-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.001</span>, <span class="at">to =</span> <span class="fl">0.999</span>, <span class="at">length =</span> <span class="dv">500</span>)</span>
<span id="cb20-2"><a href="example-2-power-of-a-test.html#cb20-2" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">2.1</span></span>
<span id="cb20-3"><a href="example-2-power-of-a-test.html#cb20-3" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb20-4"><a href="example-2-power-of-a-test.html#cb20-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">150</span></span>
<span id="cb20-5"><a href="example-2-power-of-a-test.html#cb20-5" tabindex="-1"></a></span>
<span id="cb20-6"><a href="example-2-power-of-a-test.html#cb20-6" tabindex="-1"></a>lcv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb20-7"><a href="example-2-power-of-a-test.html#cb20-7" tabindex="-1"></a>ucv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb20-8"><a href="example-2-power-of-a-test.html#cb20-8" tabindex="-1"></a></span>
<span id="cb20-9"><a href="example-2-power-of-a-test.html#cb20-9" tabindex="-1"></a>Power <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(lcv, mu, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n)) <span class="sc">+</span> <span class="fu">pnorm</span>(ucv, mu, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n), <span class="at">lower =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-10"><a href="example-2-power-of-a-test.html#cb20-10" tabindex="-1"></a></span>
<span id="cb20-11"><a href="example-2-power-of-a-test.html#cb20-11" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mu, Power)</span></code></pre></div>
</div>
<div class="webex-solution">
<button>
Plot Solution
</button>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="example-2-power-of-a-test.html#cb21-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> DF, <span class="fu">aes</span>(<span class="at">x =</span> alpha, <span class="at">y =</span> Power)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="example-2-power-of-a-test.html#cb21-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="example-2-power-of-a-test.html#cb21-3" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="example-2-power-of-a-test.html#cb21-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(alpha), <span class="at">y =</span> <span class="fu">expression</span>(Power<span class="sc">~</span>(alpha))) <span class="sc">+</span></span>
<span id="cb21-5"><a href="example-2-power-of-a-test.html#cb21-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
</div>
<div id="question-3" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> <strong>Question 3</strong><a href="example-2-power-of-a-test.html#question-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Graphically depict the power for testing <span class="math inline">\(H_0 : \mu = 2\)</span> versus <span class="math inline">\(H_1 : \mu \neq 2\)</span> when <span class="math inline">\(\mu_1 = 2.1\)</span>
and <span class="math inline">\(\alpha = 0.05\)</span> for values of <span class="math inline">\(n\)</span> ranging from 1 to 500.</p>
<div class="webex-solution">
<button>
Hint 1
</button>
<p>Think about whether you are doing a one or two-tailed test and what values represent rejecting or no-rejecting them.</p>
</div>
<div class="webex-solution">
<button>
Hint 2
</button>
<p>First make a vector of values of <span class="math inline">\(n\)</span>.</p>
<p>Then you will need to find the confidence values for each <span class="math inline">\(n\)</span> which are used to calculate the corresponding test powers.</p>
<p>The power values could be to be written as a data frame to make the plotting easier.</p>
</div>
<div class="webex-solution">
<button>
Calculations Solution
</button>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="example-2-power-of-a-test.html#cb22-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">500</span></span>
<span id="cb22-2"><a href="example-2-power-of-a-test.html#cb22-2" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">2.1</span></span>
<span id="cb22-3"><a href="example-2-power-of-a-test.html#cb22-3" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb22-4"><a href="example-2-power-of-a-test.html#cb22-4" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb22-5"><a href="example-2-power-of-a-test.html#cb22-5" tabindex="-1"></a></span>
<span id="cb22-6"><a href="example-2-power-of-a-test.html#cb22-6" tabindex="-1"></a>lcv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb22-7"><a href="example-2-power-of-a-test.html#cb22-7" tabindex="-1"></a>ucv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb22-8"><a href="example-2-power-of-a-test.html#cb22-8" tabindex="-1"></a></span>
<span id="cb22-9"><a href="example-2-power-of-a-test.html#cb22-9" tabindex="-1"></a>Power <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(lcv, mu, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n)) <span class="sc">+</span> <span class="fu">pnorm</span>(ucv, mu, sigma<span class="sc">/</span><span class="fu">sqrt</span>(n), <span class="at">lower =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-10"><a href="example-2-power-of-a-test.html#cb22-10" tabindex="-1"></a></span>
<span id="cb22-11"><a href="example-2-power-of-a-test.html#cb22-11" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mu, Power)</span></code></pre></div>
</div>
<div class="webex-solution">
<button>
Plot Solution
</button>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="example-2-power-of-a-test.html#cb23-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> DF, <span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> Power)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="example-2-power-of-a-test.html#cb23-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="example-2-power-of-a-test.html#cb23-3" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="example-2-power-of-a-test.html#cb23-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(n), <span class="at">y =</span> <span class="fu">expression</span>(Power<span class="sc">~</span>(n))) <span class="sc">+</span></span>
<span id="cb23-5"><a href="example-2-power-of-a-test.html#cb23-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
</div>
<div id="question-4" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> <strong>Question 4</strong><a href="example-2-power-of-a-test.html#question-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Think about each scenario above and select the true statements:</p>
<p>Question 1 - Varying mean</p>
<div id="radio_SVMLDHDBHA" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_SVMLDHDBHA" value=""></input> <span>For a fixed value of n and significance level alpha, the power of a test increases as the true mean moves closer from the hypothesized mean.</span></label><label><input type="radio" autocomplete="off" name="radio_SVMLDHDBHA" value=""></input> <span>For a fixed value of n and significance level alpha, the power of a test decreases as the true mean moves farther from the hypothesized mean.</span></label><label><input type="radio" autocomplete="off" name="radio_SVMLDHDBHA" value="answer"></input> <span>For a fixed value of n and significance level alpha, the power of a test increases as the true mean moves farther from the hypothesized mean.</span></label>
</div>
<p>Question 2 - Varying significance level <span class="math inline">\(\alpha\)</span></p>
<div id="radio_BAVNCGYRBF" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_BAVNCGYRBF" value="answer"></input> <span>When the sample size is fixed, the power of a test increases as the level of alpha increases</span></label><label><input type="radio" autocomplete="off" name="radio_BAVNCGYRBF" value=""></input> <span>When the sample size is fixed, the power of a test decreases as the level of alpha increases</span></label>
</div>
<p>Question 3 - Varying sample size <span class="math inline">\(n\)</span></p>
<div id="radio_YUXIQVOPBR" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_YUXIQVOPBR" value="answer"></input> <span>When the significance level of the test is fixed, the power of the test increases as the sample size increases</span></label><label><input type="radio" autocomplete="off" name="radio_YUXIQVOPBR" value=""></input> <span>When the significance level of the test is fixed, the power of the test decreases as the sample size increases</span></label>
</div>

<p>Using the data frame <code>Fertilize</code> in the package <code>PASWR</code>, which contains the height in inches for plants for cross fertilization and self-fertilization, test if the data suggest that the average height of self-fertilized plants is more than 17 inches. (Use <span class="math inline">\(\alpha = 0.05\)</span>).</p>
<ol style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>Does this data fit the required assumption of normality to perform a hypothesis test?</li>
</ol></li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<p>1 a) We can verify the normality assumption of the data using exploratory data analysis (<code>EDA()</code>).</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="example-2-power-of-a-test.html#cb24-1" tabindex="-1"></a><span class="fu">library</span>(PASWR)</span>
<span id="cb24-2"><a href="example-2-power-of-a-test.html#cb24-2" tabindex="-1"></a>FERTILIZE <span class="ot">&lt;-</span> Fertilize</span>
<span id="cb24-3"><a href="example-2-power-of-a-test.html#cb24-3" tabindex="-1"></a><span class="fu">EDA</span>(FERTILIZE<span class="sc">$</span>self)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre><code>## Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
##   15.000    0.000   12.750   16.375   17.575   18.000   17.575   18.625 
##      Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
##   20.375    2.052    4.209    0.530    2.250    7.625   -0.262   -0.647 
## SW p-val 
##    0.377</code></pre>
<p>The results from applying the function <code>EDA()</code> to self fertilized plants suggest it is not unreasonable to assume that plant height for self fertilized plants follows a normal distribution. Now, proceed with the five-step procedure.</p>
</div>
<ol style="list-style-type: decimal">
<li><ol start="2" style="list-style-type: lower-alpha">
<li>Step 1 - select the correct hypothesis:</li>
</ol></li>
</ol>
<p>To test whether the height of self fertilized plants is greater than <span class="math inline">\(17\)</span> inches, the hypotheses are:</p>
<p><span class="math display">\[H_0 : \mu = 17 \quad \text{verses} \quad H_1 : \mu &lt; 17\]</span>
<span class="math display">\[H_0 : \mu = 17 \quad \text{verses} \quad H_1 : \mu &gt; 17\]</span>
<span class="math display">\[H_0 : \mu = 17 \quad \text{verses} \quad H_1 : \mu \neq 17\]</span></p>
<ol style="list-style-type: decimal">
<li><ol start="3" style="list-style-type: lower-alpha">
<li>Step 2 - Choose and calculate the test statistic (before standardisation).</li>
</ol></li>
</ol>
<p>The test statistic <span class="math inline">\(\bar{X}=\)</span></p>
<div class="webex-solution">
<button>
Solution
</button>
<ol style="list-style-type: decimal">
<li><ol start="3" style="list-style-type: lower-alpha">
<li>The test statistic chosen is <span class="math inline">\(\bar{X}\)</span> because <span class="math inline">\(E[\bar{X}] = \mu\)</span>.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="example-2-power-of-a-test.html#cb26-1" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(FERTILIZE<span class="sc">$</span>self)</span>
<span id="cb26-2"><a href="example-2-power-of-a-test.html#cb26-2" tabindex="-1"></a>xbar</span></code></pre></div>
<pre><code>## [1] 17.575</code></pre>
<p>The value of this test statistic is <span class="math inline">\(\bar{x} = \frac{\sum^n_{i=1}x_i}{n} = 17.575\)</span></p>
</div>
<ol style="list-style-type: decimal">
<li><ol start="4" style="list-style-type: lower-alpha">
<li>Step 3a - Finding rejection region <span class="math inline">\(t_{obs} &gt; t_{1-0.05; df}\)</span>.</li>
</ol></li>
</ol>
<ol style="list-style-type: lower-roman">
<li><p>Find the degrees of freedom.</p></li>
<li><p>Find the critical value <span class="math inline">\(t_{1-0.05; df} =\)</span></p></li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<ol style="list-style-type: decimal">
<li><ol start="4" style="list-style-type: lower-alpha">
<li><ol style="list-style-type: lower-roman">
<li>Because the standardized test statistic is distributed <span class="math inline">\(t_{14}\)</span> and <span class="math inline">\(H_1\)</span> is a upper one-sided hypothesis, the rejection region is the <span class="math inline">\(t_{obs} &gt; t_{1-0.05; 14} = t_{0.95; 14}\)</span></li>
</ol></li>
</ol></li>
<li><ol start="4" style="list-style-type: lower-alpha">
<li><ol start="2" style="list-style-type: lower-roman">
<li>From the statistical tables, the t-value that corresponds to our significance level (critical value), <span class="math inline">\(t_{0.95; 14} = 1.7613\)</span>. Remember this is positive because we are discussing the upper tail of the t-distribution.</li>
</ol></li>
</ol></li>
</ol>
<p>This same t-value can be found using R:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="example-2-power-of-a-test.html#cb28-1" tabindex="-1"></a>RR <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">14</span>)</span>
<span id="cb28-2"><a href="example-2-power-of-a-test.html#cb28-2" tabindex="-1"></a>RR</span></code></pre></div>
<pre><code>## [1] 1.76131</code></pre>
</div>
<ol style="list-style-type: decimal">
<li><ol start="5" style="list-style-type: lower-alpha">
<li>Step 3b - Finding the standardisied test statistic and p-value for our data.</li>
</ol></li>
</ol>
<p>The standardized test statistic under the assumption that <span class="math inline">\(H_0\)</span> is true and its distribution are <span class="math inline">\(\frac{\bar{X}−\mu_0}{S/\sqrt{n}} \sim t_{df}\)</span>.</p>
<ol style="list-style-type: lower-roman">
<li>Calculate the standardisied test statistic.</li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<ol style="list-style-type: decimal">
<li><ol start="5" style="list-style-type: lower-alpha">
<li><ol style="list-style-type: lower-roman">
<li>Our standardised test statistic = <span class="math inline">\(\frac{\bar{X}−\mu_0}{S/\sqrt{n}} = \frac{17.575−17}{S/\sqrt{n}}\)</span>.
From our data set in R we can obtain <span class="math inline">\(S\)</span> and <span class="math inline">\(n\)</span>:</li>
</ol></li>
</ol></li>
</ol>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="example-2-power-of-a-test.html#cb30-1" tabindex="-1"></a>S <span class="ot">&lt;-</span> <span class="fu">sd</span>(FERTILIZE<span class="sc">$</span>self)</span>
<span id="cb30-2"><a href="example-2-power-of-a-test.html#cb30-2" tabindex="-1"></a>S</span></code></pre></div>
<pre><code>## [1] 2.051676</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="example-2-power-of-a-test.html#cb32-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(FERTILIZE<span class="sc">$</span>self)</span>
<span id="cb32-2"><a href="example-2-power-of-a-test.html#cb32-2" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 15</code></pre>
<p>This gives our standardised test statistic <span class="math inline">\(t_{obs}=\frac{\bar{X}−\mu_0}{S/\sqrt{n}} = 1.0854\)</span>:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="example-2-power-of-a-test.html#cb34-1" tabindex="-1"></a>sta.test.stat <span class="ot">&lt;-</span> (<span class="fl">17.575</span><span class="dv">-17</span>)<span class="sc">/</span>(S<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb34-2"><a href="example-2-power-of-a-test.html#cb34-2" tabindex="-1"></a>sta.test.stat</span></code></pre></div>
<pre><code>## [1] 1.085437</code></pre>
<p><strong>OR</strong></p>
<p>The standardised test statistic can be found using:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="example-2-power-of-a-test.html#cb36-1" tabindex="-1"></a>Test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(FERTILIZE<span class="sc">$</span>self, <span class="at">mu =</span> <span class="dv">17</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span>
<span id="cb36-2"><a href="example-2-power-of-a-test.html#cb36-2" tabindex="-1"></a>Test</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  FERTILIZE$self
## t = 1.0854, df = 14, p-value = 0.148
## alternative hypothesis: true mean is greater than 17
## 95 percent confidence interval:
##  16.64196      Inf
## sample estimates:
## mean of x 
##    17.575</code></pre>
</div>
<ol start="2" style="list-style-type: lower-roman">
<li>Calculate the p-value that corresponds to our standardised test statistic.</li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<ol style="list-style-type: decimal">
<li><ol start="5" style="list-style-type: lower-alpha">
<li><ol start="2" style="list-style-type: lower-roman">
<li></li>
</ol></li>
</ol></li>
</ol>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="example-2-power-of-a-test.html#cb38-1" tabindex="-1"></a>pvalue <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(<span class="fl">1.085437</span>, <span class="at">df=</span><span class="dv">14</span>)</span>
<span id="cb38-2"><a href="example-2-power-of-a-test.html#cb38-2" tabindex="-1"></a>pvalue</span></code></pre></div>
<pre><code>## [1] 0.1480328</code></pre>
<p>Graphically this could be shown:
<img src="_main_files/figure-html/unnamed-chunk-31-1.png" width="672" />
Our standardised test statistic is greater than the critical value and outside our rejection region. Hence our p-value is greater than <span class="math inline">\(\alpha\)</span></p>
<p><strong>OR</strong></p>
<p>The p-value can be found using:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="example-2-power-of-a-test.html#cb40-1" tabindex="-1"></a>Test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(FERTILIZE<span class="sc">$</span>self, <span class="at">mu =</span> <span class="dv">17</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span>
<span id="cb40-2"><a href="example-2-power-of-a-test.html#cb40-2" tabindex="-1"></a>Test</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  FERTILIZE$self
## t = 1.0854, df = 14, p-value = 0.148
## alternative hypothesis: true mean is greater than 17
## 95 percent confidence interval:
##  16.64196      Inf
## sample estimates:
## mean of x 
##    17.575</code></pre>
</div>
<ol style="list-style-type: decimal">
<li><ol start="6" style="list-style-type: lower-alpha">
<li>Step 4 - Statistical Conclusion</li>
</ol></li>
</ol>
<p>Do we reject our null hypothesis?</p>
<div class="webex-solution">
<button>
Solution
</button>
<ol style="list-style-type: decimal">
<li><ol start="6" style="list-style-type: lower-alpha">
<li>I. From the rejection region, we fail to reject <span class="math inline">\(H_0\)</span> because the standardised test statistic is less than the critical value and hence outside the rejection region i.e <span class="math inline">\(t_{obs} = 1.0854 &lt; 1.7613\)</span>.</li>
</ol></li>
</ol>
<p>OR</p>
<ol start="2" style="list-style-type: upper-roman">
<li>From the p-value, we fail to reject <span class="math inline">\(H_0\)</span> because the p-value<span class="math inline">\(0.1480 &gt; 0.05\)</span>.</li>
</ol>
<p>Whichever method we use, we fail to reject <span class="math inline">\(H_0\)</span>.</p>
</div>
<ol style="list-style-type: decimal">
<li><ol start="7" style="list-style-type: lower-alpha">
<li>Step 5 - English Conclusion</li>
</ol></li>
</ol>
<p>Is there statistical evidence to suggest a mean greater than 17?</p>
<div id="radio_XDAGQKCOLJ" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_XDAGQKCOLJ" value=""></input> <span>There is sufficient evidence to suggest the average height of self-fertilized plants is more than 17 inches</span></label><label><input type="radio" autocomplete="off" name="radio_XDAGQKCOLJ" value=""></input> <span>We cannot conclude if there is sufficient evidence to suggest the average height of self-fertilized plants is more than 17 inches.</span></label><label><input type="radio" autocomplete="off" name="radio_XDAGQKCOLJ" value="answer"></input> <span>There is not sufficient evidence to suggest the the average height of self-fertilized plants is more than 17 inches.</span></label><label><input type="radio" autocomplete="off" name="radio_XDAGQKCOLJ" value=""></input> <span>There is sufficient evidence to suggest the average height of self-fertilized plants is less than 17 inches.</span></label>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="example-1-the-5-steps-of-hypothesis-testing.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
