<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Exercise 1: Hubble Telescope Hypothesis Test | Lab 2 - Hypothesis Testing for the Difference in Means</title>
  <meta name="description" content="4 Exercise 1: Hubble Telescope Hypothesis Test | Lab 2 - Hypothesis Testing for the Difference in Means" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Exercise 1: Hubble Telescope Hypothesis Test | Lab 2 - Hypothesis Testing for the Difference in Means" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Exercise 1: Hubble Telescope Hypothesis Test | Lab 2 - Hypothesis Testing for the Difference in Means" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="example-2-tennis-hypothesis-test.html"/>
<link rel="next" href="exam-style-questions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome to Lab 2</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#a-summary-of-the-type-of-the-hypothesis-test-used-today"><i class="fa fa-check"></i><b>1.1</b> A summary of the type of the hypothesis test used today</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html"><i class="fa fa-check"></i><b>2</b> Example 1 - Refrigerator Hypothesis Test</a>
<ul>
<li class="chapter" data-level="2.1" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#verifying-normality"><i class="fa fa-check"></i><b>2.1</b> <strong>Verifying normality</strong></a></li>
<li class="chapter" data-level="2.2" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#step-1---hypotheses"><i class="fa fa-check"></i><b>2.2</b> <strong>Step 1 - Hypotheses</strong></a></li>
<li class="chapter" data-level="2.3" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#step-2---choosing-a-test-statistic"><i class="fa fa-check"></i><b>2.3</b> <strong>Step 2 - Choosing a Test Statistic</strong></a></li>
<li class="chapter" data-level="2.4" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#step-3---hypothesis-test-calculations"><i class="fa fa-check"></i><b>2.4</b> <strong>Step 3 - Hypothesis Test Calculations</strong></a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#finding-the-rejection-region"><i class="fa fa-check"></i><b>2.4.1</b> Finding the Rejection Region</a></li>
<li class="chapter" data-level="2.4.2" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#finding-the-standardised-test-statistic-and-p-value"><i class="fa fa-check"></i><b>2.4.2</b> Finding the standardised test statistic and <span class="math inline">\(p\)</span>-value</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#step-4---statistical-conclusion"><i class="fa fa-check"></i><b>2.5</b> <strong>Step 4 - Statistical Conclusion</strong></a></li>
<li class="chapter" data-level="2.6" data-path="example-1---refrigerator-hypothesis-test.html"><a href="example-1---refrigerator-hypothesis-test.html#step-5---english-conclusion"><i class="fa fa-check"></i><b>2.6</b> <strong>Step 5 - English Conclusion</strong></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html"><i class="fa fa-check"></i><b>3</b> Example 2: Tennis Hypothesis Test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#verifying-normality-1"><i class="fa fa-check"></i><b>3.1</b> <strong>Verifying normality</strong></a></li>
<li class="chapter" data-level="3.2" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#step-1---hypotheses-1"><i class="fa fa-check"></i><b>3.2</b> <strong>Step 1 - Hypotheses</strong></a></li>
<li class="chapter" data-level="3.3" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#step-2---choosing-a-test-statistic-1"><i class="fa fa-check"></i><b>3.3</b> <strong>Step 2 - Choosing a Test Statistic</strong></a></li>
<li class="chapter" data-level="3.4" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#step-3---hypothesis-test-calculations-1"><i class="fa fa-check"></i><b>3.4</b> <strong>Step 3 - Hypothesis Test Calculations</strong></a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#finding-the-rejection-region-1"><i class="fa fa-check"></i><b>3.4.1</b> Finding the Rejection Region</a></li>
<li class="chapter" data-level="3.4.2" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#finding-the-standardised-test-statistic-and-p-value-1"><i class="fa fa-check"></i><b>3.4.2</b> Finding the standardised test statistic and <span class="math inline">\(p\)</span>-value</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#step-4---statistical-conclusion-1"><i class="fa fa-check"></i><b>3.5</b> <strong>Step 4 - Statistical Conclusion</strong></a></li>
<li class="chapter" data-level="3.6" data-path="example-2-tennis-hypothesis-test.html"><a href="example-2-tennis-hypothesis-test.html#step-5---english-conclusion-1"><i class="fa fa-check"></i><b>3.6</b> <strong>Step 5 - English Conclusion</strong></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exercise-1-hubble-telescope-hypothesis-test.html"><a href="exercise-1-hubble-telescope-hypothesis-test.html"><i class="fa fa-check"></i><b>4</b> Exercise 1: Hubble Telescope Hypothesis Test</a>
<ul>
<li class="chapter" data-level="4.1" data-path="exercise-1-hubble-telescope-hypothesis-test.html"><a href="exercise-1-hubble-telescope-hypothesis-test.html#question-is-one-team-better-than-the-other"><i class="fa fa-check"></i><b>4.1</b> Question: Is one team better than the other?</a></li>
<li class="chapter" data-level="4.2" data-path="exercise-1-hubble-telescope-hypothesis-test.html"><a href="exercise-1-hubble-telescope-hypothesis-test.html#question-can-team1-complete-the-mission-in-less-than-3-days"><i class="fa fa-check"></i><b>4.2</b> Question: Can team1 complete the mission in less than 3 days</a></li>
<li class="chapter" data-level="4.3" data-path="exercise-1-hubble-telescope-hypothesis-test.html"><a href="exercise-1-hubble-telescope-hypothesis-test.html#question-can-team2-complete-the-mission-in-less-than-3-days"><i class="fa fa-check"></i><b>4.3</b> Question: Can team2 complete the mission in less than 3 days</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="exam-style-questions.html"><a href="exam-style-questions.html"><i class="fa fa-check"></i><b>5</b> Exam Style Questions</a>
<ul>
<li class="chapter" data-level="5.1" data-path="exam-style-questions.html"><a href="exam-style-questions.html#example-1"><i class="fa fa-check"></i><b>5.1</b> Example 1</a></li>
<li class="chapter" data-level="5.2" data-path="exam-style-questions.html"><a href="exam-style-questions.html#example-2"><i class="fa fa-check"></i><b>5.2</b> Example 2</a></li>
<li class="chapter" data-level="5.3" data-path="exam-style-questions.html"><a href="exam-style-questions.html#exercise-1"><i class="fa fa-check"></i><b>5.3</b> Exercise 1</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lab 2 - Hypothesis Testing for the Difference in Means</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exercise-1-hubble-telescope-hypothesis-test" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Exercise 1: Hubble Telescope Hypothesis Test<a href="exercise-1-hubble-telescope-hypothesis-test.html#exercise-1-hubble-telescope-hypothesis-test" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The Hubble Space Telescope was put into orbit on April 25, 1990. Unfortunately, on June 25, 1990, a spherical aberration was discovered in Hubble’s primary mirror. To correct this, astronauts had to work in space. To prepare for the mission, two teams of astronauts practiced making repairs under simulated space conditions. Each team of astronauts went through 15 identical scenarios. The times to complete each scenario were recorded in days. The data are stored in the data frame <em>HUBBLE</em> in thr <code>PASWR2</code> package.</p>
<p>We will aim to answer the questions:</p>
<ol style="list-style-type: decimal">
<li><p>Is one team better than the other?</p></li>
<li><p>And if not, can both teams complete the mission in less than 3 days?</p></li>
</ol>
<p><em>Use a 5% significance level for all tests.</em></p>
<div id="question-is-one-team-better-than-the-other" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Question: Is one team better than the other?<a href="exercise-1-hubble-telescope-hypothesis-test.html#question-is-one-team-better-than-the-other" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>1a). To answer this question, should we undertake a Welch two-sample <span class="math inline">\(t\)</span>-test or a paired <span class="math inline">\(t\)</span>-test?</strong></p>
<div id="radio_UDSMZJMCTA" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_UDSMZJMCTA" value=""></input> <span>Welch test</span></label><label><input type="radio" autocomplete="off" name="radio_UDSMZJMCTA" value="answer"></input> <span>paired <span class="math inline">\(t\)</span>-test </span></label>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<p>Each team of astronauts went through 15 identical scenarios. Consequently, the repair times for the two teams are dependent. Start the analysis by verifying the normality assumption required to use a paired <span class="math inline">\(t\)</span>-test.</p>
</div>
<p><strong>1b) Does this data fit the required assumption of normality to perform a hypothesis test?</strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>We can verify the normality assumption of the data using exploratory data analysis (<code>EDA()</code>).</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb26-1" tabindex="-1"></a><span class="fu">library</span>(PASWR2)</span>
<span id="cb26-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb26-2" tabindex="-1"></a>HUBBLE <span class="ot">&lt;-</span> HUBBLE</span>
<span id="cb26-3"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb26-3" tabindex="-1"></a>Diff <span class="ot">&lt;-</span> HUBBLE<span class="sc">$</span>team1 <span class="sc">-</span> HUBBLE<span class="sc">$</span>team2</span>
<span id="cb26-4"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb26-4" tabindex="-1"></a><span class="fu">eda</span>(Diff)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre><code>## Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
##   15.000    0.000   -2.400   -0.850   -0.100   -0.400   -0.100    1.300 
##      Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
##    2.600    1.499    2.247    0.387    2.150    5.000   -1.193    0.198 
## SW p-val 
##    0.462</code></pre>
<p>The results from applying the function eda() to the differences between team1 and team2 suggest it is not unreasonable to assume the repair time differences between team1 and team2 follow a normal distribution.</p>
</div>
<p><strong>1c) For this question, which set of hypotheses below is correct?</strong></p>
<p>Let <span class="math inline">\(\mu_{T_1}\)</span> denote the mean repair times for team1, <span class="math inline">\(\mu_{T_2}\)</span> denote the mean repair times for team2, and <span class="math inline">\(\mu_D=\mu_{T_1}-\mu_{T_2}\)</span> denote the difference in mean repair times.</p>
<p>The correct null and alternative hypotheses are:</p>
<p><select class='webex-select'><option value='blank'></option><option value=''>1</option><option value=''>2</option><option value='answer'>3</option><option value=''>4</option><option value=''>5</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The question is "Is one team better than the other?" Since we do not know which one is better, the question is equivalent to testing if the average difference in repair times for team1 and team2 are different.</p>
</div>
<p><span class="math display">\[\begin{align}
1&amp;. \quad H_0 : \mu_{T_1} - \mu_{T_2} = 0 \quad \text{verses} \quad H_1 : \mu_{T_1} - \mu_{T_2} &lt; 0\\
2&amp;. \quad H_0 : \mu_{T_1} - \mu_{T_2} = 0 \quad \text{verses} \quad H_1 : \mu_{T_1} - \mu_{T_2} &gt; 0\\
3&amp;. \quad H_0 : \mu_{D}=0 \quad \text{verses} \quad H_1 : \mu_{D} \neq 0\\
4&amp;. \quad H_0 : \mu_{D}=0 \quad \text{verses} \quad H_1 : \mu_{D} &gt; 0\\
5&amp;. \quad H_0 : \mu_{D}=0 \quad \text{verses} \quad H_1 : \mu_{D} &lt; 0

\end{align}\]</span></p>
<p><strong>1d) What is the test statistic (before standardisation)?</strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<ol start="4" style="list-style-type: lower-alpha">
<li>The test statistic chosen is <span class="math inline">\(\bar{D}\)</span> because <span class="math inline">\(E[\bar{D}] = \mu_D\)</span>.</li>
</ol>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb28-1" tabindex="-1"></a>dbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(Diff)</span>
<span id="cb28-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb28-2" tabindex="-1"></a>dbar</span></code></pre></div>
<pre><code>## [1] -0.1</code></pre>
<p>The value of this test statistic is <span class="math inline">\(\bar{d} = -0.1\)</span>.</p>
</div>
<p><strong>1e) Step 3 - Rejection Region</strong></p>
<ol style="list-style-type: lower-roman">
<li><p>Calculate the degrees of freedom,<span class="math inline">\(df\)</span>.</p></li>
<li><p>Calculate the critical value for this test.</p></li>
</ol>
<div class="webex-solution">
<button>
Solution
</button>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(df = n-1 = 15-1\)</span> so the standardised test statistic is distributed <span class="math inline">\(t_{14}\)</span>. Moreover, since <span class="math inline">\(H_1\)</span> is a two-sided hypothesis, the rejection region is the <span class="math inline">\(|t_{obs}| &gt; t_{0.975; 14}\)</span>.</li>
</ol>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<ol start="2" style="list-style-type: lower-roman">
<li>From the statistical tables, the critical value (<span class="math inline">\(t\)</span>-value that corresponds to our significance level), <span class="math inline">\(t_{0.975; 14} = 2.1448\)</span>.</li>
</ol>
<p>This can be found using R:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb30-1" tabindex="-1"></a>RR <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">14</span>)</span>
<span id="cb30-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb30-2" tabindex="-1"></a>RR</span></code></pre></div>
<pre><code>## [1] 2.144787</code></pre>
</div>
<p><strong>1f) The standardised test statistic under the assumption that <span class="math inline">\(H_0\)</span> is true and its distribution are <span class="math inline">\(\frac{\bar{d}−\delta_0}{s_d/\sqrt{n_D}} \sim t_{df}\)</span>.</strong></p>
<p>Find the value of standardised test statistic and <span class="math inline">\(p\)</span>-value using <code>t.test()</code>.</p>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb32-1" tabindex="-1"></a>Diff <span class="ot">&lt;-</span> HUBBLE<span class="sc">$</span>team1 <span class="sc">-</span> HUBBLE<span class="sc">$</span>team2</span>
<span id="cb32-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb32-2" tabindex="-1"></a>t.obs <span class="ot">&lt;-</span> <span class="fu">mean</span>(Diff) <span class="sc">/</span> (<span class="fu">sd</span>(Diff)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(Diff)))</span>
<span id="cb32-3"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb32-3" tabindex="-1"></a>t.obs</span></code></pre></div>
<pre><code>## [1] -0.258363</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb34-1" tabindex="-1"></a>p.value <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(t.obs, <span class="at">df=</span><span class="fu">length</span>(Diff)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb34-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb34-2" tabindex="-1"></a>p.value</span></code></pre></div>
<pre><code>## [1] 0.7998863</code></pre>
<p>Or use <code>t.test()</code> directly:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb36-1" tabindex="-1"></a>TR <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Diff)</span>
<span id="cb36-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb36-2" tabindex="-1"></a>TR</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  Diff
## t = -0.25836, df = 14, p-value = 0.7999
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.9301447  0.7301447
## sample estimates:
## mean of x 
##      -0.1</code></pre>
<p>This gives the value of standardised test statistic as <span class="math inline">\(-0.25836\)</span> and the <span class="math inline">\(p\)</span>-value as <span class="math inline">\(0.7999\)</span>.
This code provides the <span class="math inline">\(p\)</span>-value fully adjusted for a two-tailed test.</p>
</div>
<p><strong>1g) Step 4 - Statistical Conclusion</strong></p>
<p>Do we reject our null hypothesis?</p>
<div id="radio_TFUIKTTRWO" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_TFUIKTTRWO" value=""></input> <span>From the rejection region, reject the null hypothesis because our observed <span class="math inline">\(t\)</span>-value, 0.2584, is less than 2.1448.</span></label><label><input type="radio" autocomplete="off" name="radio_TFUIKTTRWO" value="answer"></input> <span>From the rejection region, fail to reject the null hypothesis because our observed <span class="math inline">\(t\)</span>-value, 0.2584, is less than 2.1448.</span></label>
</div>
<div id="radio_NSZDUHIPSU" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_NSZDUHIPSU" value=""></input> <span>From the <span class="math inline">\(p\)</span>-value, reject our null hyphotesis because the <span class="math inline">\(p\)</span>-value 0.7999 is greater than 0.05</span></label><label><input type="radio" autocomplete="off" name="radio_NSZDUHIPSU" value="answer"></input> <span>From the <span class="math inline">\(p\)</span>-value, fail to reject our null hyphotesis because the <span class="math inline">\(p\)</span>-value 0.7999 is greater than 0.05</span></label>
</div>
<p><strong>1h) Step 5 - English Conclusion</strong></p>
<p>Is there sufficient evidence to suggest one team is better than the other?</p>
<div id="radio_MNBULWDXXB" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_MNBULWDXXB" value=""></input> <span>There is sufficient evidence to suggest the mean difference in repair times is not equal to zero. In other words, there is evidence to suggest one team is better than the other.</span></label><label><input type="radio" autocomplete="off" name="radio_MNBULWDXXB" value=""></input> <span>There is sufficient evidence to suggest the mean difference in repair times is equal to zero. In other words, there is no evidence to suggest one team is better than the other.</span></label><label><input type="radio" autocomplete="off" name="radio_MNBULWDXXB" value="answer"></input> <span>There is not sufficient evidence to suggest the mean difference in repair times is not equal to zero. In other words, there is no evidence to suggest one team is better than the other.</span></label><label><input type="radio" autocomplete="off" name="radio_MNBULWDXXB" value=""></input> <span>There is not sufficient evidence to suggest the mean difference in repair times is equal to zero. In other words, there is evidence
to suggest one team is better than the other.</span></label>
</div>
</div>
<div id="question-can-team1-complete-the-mission-in-less-than-3-days" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Question: Can team1 complete the mission in less than 3 days<a href="exercise-1-hubble-telescope-hypothesis-test.html#question-can-team1-complete-the-mission-in-less-than-3-days" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>2a) Does team1 fit the normality assumptions required?</strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>We can verify the normality assumption of the data for team1 using exploratory data analysis (<code>EDA()</code>).</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb38-1" tabindex="-1"></a><span class="fu">with</span>(<span class="at">data =</span> HUBBLE,<span class="fu">eda</span>(team1))</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre><code>## Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
##   15.000    0.000    1.000    1.500    2.220    2.400    2.220    2.850 
##      Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
##    3.600    0.800    0.640    0.207    1.350    2.600   -1.352   -0.052 
## SW p-val 
##    0.613</code></pre>
<p>The results from applying the function eda() to the repair times for team1 suggest it is not unreasonable to assume the repair times for team1 follow a normal distribution.</p>
</div>
<p><strong>2b) For this question, which set of hypotheses below is correct?</strong></p>
<p><span class="math display">\[\begin{align}
1&amp;. \quad H_0 : \mu = 3 \quad \text{verses} \quad H_1 : \mu &gt; 3\\
2&amp;. \quad H_0 : \mu = 3 \quad \text{verses} \quad H_1 : \mu \neq 3\\
3&amp;. \quad H_0 : \mu = 3 \quad \text{verses} \quad H_1 : \mu &lt; 3\\

\end{align}\]</span></p>
<p><select class='webex-select'><option value='blank'></option><option value=''>1</option><option value=''>2</option><option value='answer'>3</option></select></p>
<p><strong>2c) What is the test statistic (before standardisation)?</strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The test statistic chosen is <span class="math inline">\(\bar{X}\)</span> because <span class="math inline">\(E[\bar{X}] = \mu\)</span>.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb40-1" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(HUBBLE<span class="sc">$</span>team1)</span>
<span id="cb40-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb40-2" tabindex="-1"></a>xbar</span></code></pre></div>
<pre><code>## [1] 2.22</code></pre>
<p>The value of this test statistic is <span class="math inline">\(\bar{x} = \frac{\sum^n_{i=1}x_i}{n}= 2.22\)</span></p>
</div>
<p><strong>2d) Step 3 - Rejection Region</strong></p>
<p>Calculate the degrees of freedom,<span class="math inline">\(df\)</span> and the critical value for this test.</p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math inline">\(df = n-1 = 15-1\)</span> so the standardised test statistic is distributed <span class="math inline">\(t_{14}\)</span>, and since <span class="math inline">\(H_1\)</span> is a lower one-sided hypothesis, the rejection region is the <span class="math inline">\(t_{obs} &gt; t_{0.05; 14}\)</span></p>
<p>From the statistical tables, the critical value (<span class="math inline">\(t\)</span>-value that corresponds to our significance level) is <span class="math inline">\(t_{0.05; 14} = -1.7613\)</span>.</p>
<p>This can be found using R:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb42-1" tabindex="-1"></a>RR <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.05</span>, <span class="at">df =</span> <span class="dv">14</span>)</span>
<span id="cb42-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb42-2" tabindex="-1"></a>RR</span></code></pre></div>
<pre><code>## [1] -1.76131</code></pre>
</div>
<p><strong>2e) Find the value of standardised test statistic and <span class="math inline">\(p\)</span>-value using <code>t.test()</code>. </strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Our standardised test statistic <span class="math inline">\(= \frac{\bar{x}−\mu_0}{s/\sqrt{n}}\)</span>.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb44-1" tabindex="-1"></a>t.obs <span class="ot">&lt;-</span> (<span class="fu">mean</span>(HUBBLE<span class="sc">$</span>team1)<span class="sc">-</span><span class="dv">3</span>)<span class="sc">/</span>(<span class="fu">sd</span>(HUBBLE<span class="sc">$</span>team1)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(HUBBLE<span class="sc">$</span>team1)))</span>
<span id="cb44-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb44-2" tabindex="-1"></a>t.obs</span></code></pre></div>
<pre><code>## [1] -3.775316</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb46-1" tabindex="-1"></a>p.value <span class="ot">&lt;-</span> <span class="fu">pt</span>(t.obs, <span class="at">df=</span><span class="fu">length</span>(HUBBLE<span class="sc">$</span>team1)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb46-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb46-2" tabindex="-1"></a>p.value</span></code></pre></div>
<pre><code>## [1] 0.00102414</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb48-1" tabindex="-1"></a>TR <span class="ot">&lt;-</span> <span class="fu">with</span>(<span class="at">data =</span> HUBBLE, <span class="fu">t.test</span>(team1, <span class="at">mu =</span> <span class="dv">3</span>, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>))</span>
<span id="cb48-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb48-2" tabindex="-1"></a>TR</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  team1
## t = -3.7753, df = 14, p-value = 0.001024
## alternative hypothesis: true mean is less than 3
## 95 percent confidence interval:
##      -Inf 2.583896
## sample estimates:
## mean of x 
##      2.22</code></pre>
<p>This gives the value of standardised test statistic as <span class="math inline">\(-3.7757\)</span> and the <span class="math inline">\(p\)</span>-value <span class="math inline">\(\mathrm{P}(t_{14} \leq -3.7753) = 0.001024\)</span>.</p>
</div>
<p><strong>2f) Step 4 - Statistical Conclusion</strong></p>
<p>Do we reject our null hypothesis?</p>
<div id="radio_RPMJZKAQLJ" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_RPMJZKAQLJ" value="answer"></input> <span>From the rejection region, we reject the null hypothesis because the observed <span class="math inline">\(t\)</span>-value −3.7753 is less than −1.7613.</span></label><label><input type="radio" autocomplete="off" name="radio_RPMJZKAQLJ" value=""></input> <span>From the rejection region, we fail to reject the null hypothesis because the observed <span class="math inline">\(t\)</span>-value −3.7753 is less than −1.7613.</span></label>
</div>
<div id="radio_MSWIZZAOVP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_MSWIZZAOVP" value="answer"></input> <span>From the <span class="math inline">\(p\)</span>-value, we reject our null hyphotesis because the <span class="math inline">\(p\)</span>-value 0.0010 is less than 0.05.</span></label><label><input type="radio" autocomplete="off" name="radio_MSWIZZAOVP" value=""></input> <span>From the <span class="math inline">\(p\)</span>-value, we fail to reject our null hyphotesis because the <span class="math inline">\(p\)</span>-value 0.0010 is less than 0.05.</span></label>
</div>
<p><strong>2g) Step 5 - English Conclusion</strong></p>
<p>Is there sufficient evidence that the team1 average mission repair time in less than 3 days?</p>
<div id="radio_GJTFCOJQQF" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_GJTFCOJQQF" value=""></input> <span>There is sufficient evidence to suggest that the team1 average mission repair time is 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_GJTFCOJQQF" value=""></input> <span>There is not enough evidence to suggest that the team1 average mission repair time is less than 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_GJTFCOJQQF" value="answer"></input> <span>There is sufficient evidence to suggest that the team1 average mission repair time is less than 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_GJTFCOJQQF" value=""></input> <span>There is not enough evidence to suggest that the team1 average mission repair time is 3 days.</span></label>
</div>
</div>
<div id="question-can-team2-complete-the-mission-in-less-than-3-days" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Question: Can team2 complete the mission in less than 3 days<a href="exercise-1-hubble-telescope-hypothesis-test.html#question-can-team2-complete-the-mission-in-less-than-3-days" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>3a) Does team2 fit the normality assumptions required?</strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The exploratory data analysis below suggests that it is not unreasonable to assume the repair times for team2 follow a normal distribution.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb50-1" tabindex="-1"></a><span class="fu">with</span>(<span class="at">data =</span> HUBBLE,<span class="fu">eda</span>(team2))</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<pre><code>## Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
##   15.000    0.000    0.400    1.650    2.320    2.600    2.320    2.950 
##      Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
##    3.800    0.981    0.963    0.253    1.300    3.400   -1.074   -0.350 
## SW p-val 
##    0.848</code></pre>
</div>
<p><strong>3b) For this test, find the value of standardised test statistic and <span class="math inline">\(p\)</span>-value using <code>t.test()</code>.</strong></p>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb52-1" tabindex="-1"></a>TR <span class="ot">&lt;-</span> <span class="fu">with</span>(<span class="at">data =</span> HUBBLE, <span class="fu">t.test</span>(team2, <span class="at">mu =</span> <span class="dv">3</span>, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>))</span>
<span id="cb52-2"><a href="exercise-1-hubble-telescope-hypothesis-test.html#cb52-2" tabindex="-1"></a>TR</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  team2
## t = -2.6835, df = 14, p-value = 0.008911
## alternative hypothesis: true mean is less than 3
## 95 percent confidence interval:
##      -Inf 2.766309
## sample estimates:
## mean of x 
##      2.32</code></pre>
<p>This gives the standardised test statistic as <span class="math inline">\(-2.6835\)</span> and the <span class="math inline">\(p\)</span>-value <span class="math inline">\(\mathrm{P}(t_{14} \leq -2.6835) = 0.008911\)</span>.</p>
</div>
<p><strong>3f) Statistical Conclusion</strong></p>
<p>Do we reject the null hypothesis?</p>
<div id="radio_CTTXJDUPEB" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_CTTXJDUPEB" value="answer"></input> <span>From the rejection region, we reject the null hypothesis because the observed <span class="math inline">\(t\)</span>-value -2.6835 is less than -1.7613.</span></label><label><input type="radio" autocomplete="off" name="radio_CTTXJDUPEB" value=""></input> <span>From the rejection region, we fail to reject the null hypothesis because the observed <span class="math inline">\(t\)</span>-value -2.6835 is less than -1.7613.</span></label>
</div>
<div id="radio_KNRKSPXYZD" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_KNRKSPXYZD" value="answer"></input> <span>From the <span class="math inline">\(p\)</span>-value, we reject our null hyphotesis because the <span class="math inline">\(p\)</span>-value 0.0089 is less than 0.05</span></label><label><input type="radio" autocomplete="off" name="radio_KNRKSPXYZD" value=""></input> <span>From the <span class="math inline">\(p\)</span>-value, we fail to reject our null hyphotesis because the <span class="math inline">\(p\)</span>-value 0.0089 is less than 0.05</span></label>
</div>
<p><strong>3g) English Conclusion</strong></p>
<p>Is there sufficient evidence that the team1 average mission repair time in less than 3 days?</p>
<div id="radio_XELWOVNYOL" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_XELWOVNYOL" value=""></input> <span>There is sufficient evidence to suggest that the team2 average mission repair time is 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_XELWOVNYOL" value=""></input> <span>There is not enough evidence to suggest that the team2 average mission repair time is less than 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_XELWOVNYOL" value="answer"></input> <span>There is sufficient evidence to suggest that the team2 average mission repair time is less than 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_XELWOVNYOL" value=""></input> <span>There is not enough evidence to suggest that the team2 average mission repair time is 3 days.</span></label>
</div>
<p>This means that for Team 1 and Team 2:</p>
<div id="radio_IYLKUWNJCQ" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_IYLKUWNJCQ" value=""></input> <span>There is sufficient evidence to suggest that neither Team 1 or Team 2 complete their average mission repair time in less than 3 days.</span></label><label><input type="radio" autocomplete="off" name="radio_IYLKUWNJCQ" value=""></input> <span>There is sufficient evidence to suggest that Team 1 can complete their average mission repair time in less than 3 days while Team 2 cannot.</span></label><label><input type="radio" autocomplete="off" name="radio_IYLKUWNJCQ" value=""></input> <span>There is sufficient evidence to suggest that Team 2 can complete their average mission repair time in less than 3 days while Team 1 cannot.</span></label><label><input type="radio" autocomplete="off" name="radio_IYLKUWNJCQ" value="answer"></input> <span>There is sufficient evidence to suggest that both Team 1 and Team 2 can complete their average mission repair time in less than 3 days.</span></label>
</div>

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Check Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Check Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="example-2-tennis-hypothesis-test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exam-style-questions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["main.pdf", "main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
